//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lesson
    {
        public int Id { get; set; }
        public string Description { get; set; }
        public int ModuleId { get; set; }
        public int CourseId { get; set; }
        public Nullable<System.DateTime> LectureDate { get; set; }
        public int TeacherResourceId { get; set; }
        public int BackupResourceId { get; set; }
        public Nullable<int> ClassroomId { get; set; }
    
        public virtual Classroom Classroom { get; set; }
        public virtual Course Course { get; set; }
        public virtual Resource Backup { get; set; }
        public virtual Module Module { get; set; }
        public virtual Resource Teacher { get; set; }
    }
}
